DROP TABLE IF EXISTS feature_sets CASCADE;

DROP TABLE IF EXISTS feature_statistics CASCADE;

DROP TABLE IF EXISTS features CASCADE;

DROP TABLE IF EXISTS entities CASCADE;

DROP TABLE IF EXISTS jobs CASCADE;

DROP TABLE IF EXISTS jobs_feature_sets CASCADE;

DROP TABLE IF EXISTS jobs_stores CASCADE;

DROP TABLE IF EXISTS sources CASCADE;
