FROM openjdk:11-jre-slim

ARG REVISION=dev
COPY serving/target/feast-serving-$REVISION.jar /usr/share/feast/feast-serving.jar

# TODO: Move this to custom base image
ADD https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.1/grpc_health_probe-linux-amd64 /usr/bin/grpc-health-probe
RUN chmod +x /usr/bin/grpc-health-probe

ENV JAVA_OPTS=-XX:+UnlockExperimentalVMOptions

ENTRYPOINT java $JAVA_OPTS -jar /usr/share/feast/feast-serving.jar
