# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from feast.core import TrainingService_pb2 as feast_dot_core_dot_TrainingService__pb2


class TrainingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTrainingDataset = channel.unary_unary(
        '/feast.core.TrainingService/CreateTrainingDataset',
        request_serializer=feast_dot_core_dot_TrainingService__pb2.TrainingServiceTypes.CreateTrainingDatasetRequest.SerializeToString,
        response_deserializer=feast_dot_core_dot_TrainingService__pb2.TrainingServiceTypes.CreateTrainingDatasetResponse.FromString,
        )


class TrainingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTrainingDataset(self, request, context):
    """Create training dataset for a feature set
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTrainingDataset': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTrainingDataset,
          request_deserializer=feast_dot_core_dot_TrainingService__pb2.TrainingServiceTypes.CreateTrainingDatasetRequest.FromString,
          response_serializer=feast_dot_core_dot_TrainingService__pb2.TrainingServiceTypes.CreateTrainingDatasetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'feast.core.TrainingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
