version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - ginkgolinter
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - kubeapilinter
  settings:
    revive:
      rules:
        - name: comment-spacings
    custom:
      kubeapilinter:
        type: module
        description: Kube API Linter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
              - "*"
            enable:
              - commentstart
              - optionalorrequired
              - defaults
              - nonpointerstructs
              - conditions
          lintersConfig: {}
  exclusions:
    rules:
      - path: "api/.*"
        linters:
          - lll
      - path: "internal/.*"
        linters:
          - dupl
          - lll
      - path: "test/.*"
        linters:
          - lll
      - path: "upgrade/.*"
        linters:
          - lll
      - path: "previous-version/.*"
        linters:
          - lll
      - path-except: "api/.*"
        linters:
          - kubeapilinter

formatters:
  enable:
    - gofmt
    - goimports
