FROM sdist-builder:latest

COPY requirements.txt requirements.txt
USER 1001
RUN source /tmp/cachi2.env && \
    pip install --no-binary :all: pandas && \
    # pip install --no-binary :all: .[aws,gcp,snowflake,redis,go,mysql,postgres,opentelemetry,grpcio,k8s,duckdb,milvus]
    pip install --no-binary :all: -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json
