FROM ibis-builder:latest

RUN source /tmp/cachi2.env && \
    pip install --no-binary :all: setuptools-rust

COPY --chown=default . ${APP_ROOT}/src/maturin

WORKDIR ${APP_ROOT}/src/maturin
RUN source /tmp/cachi2.env && \
    python setup.py install

WORKDIR ${APP_ROOT}/src
RUN rm -rf ${APP_ROOT}/src/maturin
