FROM registry.access.redhat.com/ubi9/python-311:9.5

COPY --chown=default . ${APP_ROOT}/src

RUN pip install --no-cache-dir pip-tools
RUN make install-python-ci-dependencies

RUN npm install -S yarn
ENV PATH ${PATH}:${APP_ROOT}/src/node_modules/yarn/bin
RUN make build-ui

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json
