# replicaCount -- Number of pods that will be created
replicaCount: 1

image:
  # image.repository -- Docker image for Feature Server repository
  repository: quay.io/feastdev/feature-server
  # image.tag -- Image tag
  tag: 0.65.0
  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent

# feature_store_yaml_base64 -- [required] a base64 encoded version of feature_store.yaml
feature_store_yaml_base64: ""

livenessProbe:
  # livenessProbe.enabled -- Flag to enabled the probe
  enabled: true
  # livenessProbe.initialDelaySeconds -- Delay before the probe is initiated
  initialDelaySeconds: 60
  # livenessProbe.periodSeconds -- How often to perform the probe
  periodSeconds: 10
  # livenessProbe.timeoutSeconds -- When the probe times out
  timeoutSeconds: 5
  # livenessProbe.successThreshold -- Min consecutive success for the probe to be considered successful
  successThreshold: 1
  # livenessProbe.failureThreshold -- Min consecutive failures for the probe to be considered failed
  failureThreshold: 5

readinessProbe:
  # readinessProbe.enabled -- Flag to enabled the probe
  enabled: true
  # readinessProbe.initialDelaySeconds -- Delay before the probe is initiated
  initialDelaySeconds: 15
  # readinessProbe.periodSeconds -- How often to perform the probe
  periodSeconds: 10
  # readinessProbe.timeoutSeconds -- When the probe times out
  timeoutSeconds: 10
  # readinessProbe.successThreshold -- Min consecutive success for the probe to be considered successful
  successThreshold: 1
  # readinessProbe.failureThreshold -- Min consecutive failures for the probe to be considered failed
  failureThreshold: 5

service:
  # service.type -- Kubernetes service type
  type: ClusterIP
  # service.port -- Service port
  port: 6566
  # service.nodePort -- Port number that each cluster node will listen to
  nodePort:
  # service.loadBalancerIP -- Specify a load balancer IP if service type is LoadBalancer
  loadBalancerIP:
  # service.loadBalancerSourceRanges -- Optionally restrict load balancer traffic to specified IPs
  loadBalancerSourceRanges: []

# resources -- CPU/memory [resource requests/limit](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container)
resources: {}

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}

# envOverrides -- Extra environment variables to set
envOverrides: {}

# secrets -- List of Kubernetes secrets to be mounted. These secrets will be mounted on /etc/secrets/<secret name>.
secrets: []

# podAnnotations -- Annotations to be added to Feast Serving pods
podAnnotations: {}

# podLabels -- Labels to be added to Feast Serving pods
podLabels: {}
