FROM yarn-builder:latest

COPY requirements.txt requirements.txt
RUN source /tmp/hermeto.env && \
    pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json
