FROM pip-builder:latest

# ibis-framework must build from its own git repo... versioning requirement
RUN cd ${APP_ROOT}/src/ibis && \
    source /tmp/cachi2.env && \
    pip install --no-binary :all: .[duckdb] && \
    cd ${APP_ROOT}/src && \
    rm -rf ${APP_ROOT}/src/ibis
