package feast.core.job.databricks;

public enum DatabricksJobState {
    JOB_STATE_PENDING,
    JOB_STATE_RUNNING,
    JOB_STATE_TERMINATING,
    JOB_STATE_TERMINATED_SUCCESS,
    JOB_STATE_TERMINATED_FAILED,
    JOB_STATE_TERMINATED_TIMEDOUT,
    JOB_STATE_TERMINATED_CANCELED,
    JOB_STATE_SKIPPED,
    JOB_STATE_INTERNAL_ERROR
}
