package feast.core.job.databricks;

public enum DatabricksJobState {
    PENDING,
    RUNNING,
    TERMINATING,
    TERMINATED_SUCCESS,
    TERMINATED_FAILED,
    TERMINATED_TIMEDOUT,
    TERMINATED_CANCELED,
    SKIPPED,
    INTERNAL_ERROR,
    INTERNAL_ERROR_FAILED
}
