"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from feast.core import DataSource_pb2 as _DataSource_pb2
from feast.core import Entity_pb2 as _Entity_pb2
from feast.core import FeatureService_pb2 as _FeatureService_pb2
from feast.core import FeatureView_pb2 as _FeatureView_pb2
from feast.core import InfraObject_pb2 as _InfraObject_pb2
from feast.core import OnDemandFeatureView_pb2 as _OnDemandFeatureView_pb2
from feast.core import Permission_pb2 as _Permission_pb2
from feast.core import Project_pb2 as _Project_pb2
from feast.core import Registry_pb2 as _Registry_pb2
from feast.core import SavedDataset_pb2 as _SavedDataset_pb2
from feast.core import StreamFeatureView_pb2 as _StreamFeatureView_pb2
from feast.core import ValidationProfile_pb2 as _ValidationProfile_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PaginationParams(_message.Message):
    """Common pagination and sorting messages"""

    DESCRIPTOR: _descriptor.Descriptor

    PAGE_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    page: _builtins.int
    """1-based page number"""
    limit: _builtins.int
    """Number of items per page"""
    def __init__(
        self,
        *,
        page: _builtins.int = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "page", b"page"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PaginationParams: _TypeAlias = PaginationParams  # noqa: Y015

@_typing.final
class SortingParams(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SORT_BY_FIELD_NUMBER: _builtins.int
    SORT_ORDER_FIELD_NUMBER: _builtins.int
    sort_by: _builtins.str
    """Field to sort by (supports dot notation)"""
    sort_order: _builtins.str
    """"asc" or "desc" """
    def __init__(
        self,
        *,
        sort_by: _builtins.str = ...,
        sort_order: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sort_by", b"sort_by", "sort_order", b"sort_order"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SortingParams: _TypeAlias = SortingParams  # noqa: Y015

@_typing.final
class PaginationMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGE_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    TOTAL_COUNT_FIELD_NUMBER: _builtins.int
    TOTAL_PAGES_FIELD_NUMBER: _builtins.int
    HAS_NEXT_FIELD_NUMBER: _builtins.int
    HAS_PREVIOUS_FIELD_NUMBER: _builtins.int
    page: _builtins.int
    limit: _builtins.int
    total_count: _builtins.int
    total_pages: _builtins.int
    has_next: _builtins.bool
    has_previous: _builtins.bool
    def __init__(
        self,
        *,
        page: _builtins.int = ...,
        limit: _builtins.int = ...,
        total_count: _builtins.int = ...,
        total_pages: _builtins.int = ...,
        has_next: _builtins.bool = ...,
        has_previous: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_next", b"has_next", "has_previous", b"has_previous", "limit", b"limit", "page", b"page", "total_count", b"total_count", "total_pages", b"total_pages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PaginationMetadata: _TypeAlias = PaginationMetadata  # noqa: Y015

@_typing.final
class RefreshRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RefreshRequest: _TypeAlias = RefreshRequest  # noqa: Y015

@_typing.final
class UpdateInfraRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INFRA_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def infra(self) -> _InfraObject_pb2.Infra: ...
    def __init__(
        self,
        *,
        infra: _InfraObject_pb2.Infra | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["infra", b"infra"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "infra", b"infra", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateInfraRequest: _TypeAlias = UpdateInfraRequest  # noqa: Y015

@_typing.final
class GetInfraRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetInfraRequest: _TypeAlias = GetInfraRequest  # noqa: Y015

@_typing.final
class ListProjectMetadataRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListProjectMetadataRequest: _TypeAlias = ListProjectMetadataRequest  # noqa: Y015

@_typing.final
class ListProjectMetadataResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def project_metadata(self) -> _containers.RepeatedCompositeFieldContainer[_Registry_pb2.ProjectMetadata]: ...
    def __init__(
        self,
        *,
        project_metadata: _abc.Iterable[_Registry_pb2.ProjectMetadata] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["project_metadata", b"project_metadata"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListProjectMetadataResponse: _TypeAlias = ListProjectMetadataResponse  # noqa: Y015

@_typing.final
class ApplyMaterializationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    START_DATE_FIELD_NUMBER: _builtins.int
    END_DATE_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def feature_view(self) -> _FeatureView_pb2.FeatureView: ...
    @_builtins.property
    def start_date(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def end_date(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        feature_view: _FeatureView_pb2.FeatureView | None = ...,
        project: _builtins.str = ...,
        start_date: _timestamp_pb2.Timestamp | None = ...,
        end_date: _timestamp_pb2.Timestamp | None = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_date", b"end_date", "feature_view", b"feature_view", "start_date", b"start_date"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "end_date", b"end_date", "feature_view", b"feature_view", "project", b"project", "start_date", b"start_date"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyMaterializationRequest: _TypeAlias = ApplyMaterializationRequest  # noqa: Y015

@_typing.final
class ApplyEntityRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTITY_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def entity(self) -> _Entity_pb2.Entity: ...
    def __init__(
        self,
        *,
        entity: _Entity_pb2.Entity | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entity", b"entity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "entity", b"entity", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyEntityRequest: _TypeAlias = ApplyEntityRequest  # noqa: Y015

@_typing.final
class GetEntityRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetEntityRequest: _TypeAlias = GetEntityRequest  # noqa: Y015

@_typing.final
class ListEntitiesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListEntitiesRequest: _TypeAlias = ListEntitiesRequest  # noqa: Y015

@_typing.final
class ListEntitiesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTITIES_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entities(self) -> _containers.RepeatedCompositeFieldContainer[_Entity_pb2.Entity]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        entities: _abc.Iterable[_Entity_pb2.Entity] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entities", b"entities", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListEntitiesResponse: _TypeAlias = ListEntitiesResponse  # noqa: Y015

@_typing.final
class DeleteEntityRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteEntityRequest: _TypeAlias = DeleteEntityRequest  # noqa: Y015

@_typing.final
class ApplyDataSourceRequest(_message.Message):
    """DataSources"""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_SOURCE_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def data_source(self) -> _DataSource_pb2.DataSource: ...
    def __init__(
        self,
        *,
        data_source: _DataSource_pb2.DataSource | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data_source", b"data_source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "data_source", b"data_source", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyDataSourceRequest: _TypeAlias = ApplyDataSourceRequest  # noqa: Y015

@_typing.final
class GetDataSourceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetDataSourceRequest: _TypeAlias = GetDataSourceRequest  # noqa: Y015

@_typing.final
class ListDataSourcesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListDataSourcesRequest: _TypeAlias = ListDataSourcesRequest  # noqa: Y015

@_typing.final
class ListDataSourcesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_SOURCES_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def data_sources(self) -> _containers.RepeatedCompositeFieldContainer[_DataSource_pb2.DataSource]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        data_sources: _abc.Iterable[_DataSource_pb2.DataSource] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_sources", b"data_sources", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListDataSourcesResponse: _TypeAlias = ListDataSourcesResponse  # noqa: Y015

@_typing.final
class DeleteDataSourceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteDataSourceRequest: _TypeAlias = DeleteDataSourceRequest  # noqa: Y015

@_typing.final
class ApplyFeatureViewRequest(_message.Message):
    """FeatureViews"""

    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    ON_DEMAND_FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    STREAM_FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def feature_view(self) -> _FeatureView_pb2.FeatureView: ...
    @_builtins.property
    def on_demand_feature_view(self) -> _OnDemandFeatureView_pb2.OnDemandFeatureView: ...
    @_builtins.property
    def stream_feature_view(self) -> _StreamFeatureView_pb2.StreamFeatureView: ...
    def __init__(
        self,
        *,
        feature_view: _FeatureView_pb2.FeatureView | None = ...,
        on_demand_feature_view: _OnDemandFeatureView_pb2.OnDemandFeatureView | None = ...,
        stream_feature_view: _StreamFeatureView_pb2.StreamFeatureView | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base_feature_view", b"base_feature_view", "feature_view", b"feature_view", "on_demand_feature_view", b"on_demand_feature_view", "stream_feature_view", b"stream_feature_view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base_feature_view", b"base_feature_view", "commit", b"commit", "feature_view", b"feature_view", "on_demand_feature_view", b"on_demand_feature_view", "project", b"project", "stream_feature_view", b"stream_feature_view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_base_feature_view: _TypeAlias = _typing.Literal["feature_view", "on_demand_feature_view", "stream_feature_view"]  # noqa: Y015
    _WhichOneofArgType_base_feature_view: _TypeAlias = _typing.Literal["base_feature_view", b"base_feature_view"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_base_feature_view) -> _WhichOneofReturnType_base_feature_view | None: ...

Global___ApplyFeatureViewRequest: _TypeAlias = ApplyFeatureViewRequest  # noqa: Y015

@_typing.final
class GetFeatureViewRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFeatureViewRequest: _TypeAlias = GetFeatureViewRequest  # noqa: Y015

@_typing.final
class ListFeatureViewsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeatureViewsRequest: _TypeAlias = ListFeatureViewsRequest  # noqa: Y015

@_typing.final
class ListFeatureViewsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEWS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_views(self) -> _containers.RepeatedCompositeFieldContainer[_FeatureView_pb2.FeatureView]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        feature_views: _abc.Iterable[_FeatureView_pb2.FeatureView] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_views", b"feature_views", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeatureViewsResponse: _TypeAlias = ListFeatureViewsResponse  # noqa: Y015

@_typing.final
class DeleteFeatureViewRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteFeatureViewRequest: _TypeAlias = DeleteFeatureViewRequest  # noqa: Y015

@_typing.final
class AnyFeatureView(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    ON_DEMAND_FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    STREAM_FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_view(self) -> _FeatureView_pb2.FeatureView: ...
    @_builtins.property
    def on_demand_feature_view(self) -> _OnDemandFeatureView_pb2.OnDemandFeatureView: ...
    @_builtins.property
    def stream_feature_view(self) -> _StreamFeatureView_pb2.StreamFeatureView: ...
    def __init__(
        self,
        *,
        feature_view: _FeatureView_pb2.FeatureView | None = ...,
        on_demand_feature_view: _OnDemandFeatureView_pb2.OnDemandFeatureView | None = ...,
        stream_feature_view: _StreamFeatureView_pb2.StreamFeatureView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["any_feature_view", b"any_feature_view", "feature_view", b"feature_view", "on_demand_feature_view", b"on_demand_feature_view", "stream_feature_view", b"stream_feature_view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["any_feature_view", b"any_feature_view", "feature_view", b"feature_view", "on_demand_feature_view", b"on_demand_feature_view", "stream_feature_view", b"stream_feature_view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_any_feature_view: _TypeAlias = _typing.Literal["feature_view", "on_demand_feature_view", "stream_feature_view"]  # noqa: Y015
    _WhichOneofArgType_any_feature_view: _TypeAlias = _typing.Literal["any_feature_view", b"any_feature_view"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_any_feature_view) -> _WhichOneofReturnType_any_feature_view | None: ...

Global___AnyFeatureView: _TypeAlias = AnyFeatureView  # noqa: Y015

@_typing.final
class GetAnyFeatureViewRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAnyFeatureViewRequest: _TypeAlias = GetAnyFeatureViewRequest  # noqa: Y015

@_typing.final
class GetAnyFeatureViewResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ANY_FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def any_feature_view(self) -> Global___AnyFeatureView: ...
    def __init__(
        self,
        *,
        any_feature_view: Global___AnyFeatureView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["any_feature_view", b"any_feature_view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["any_feature_view", b"any_feature_view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAnyFeatureViewResponse: _TypeAlias = GetAnyFeatureViewResponse  # noqa: Y015

@_typing.final
class ListAllFeatureViewsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    ENTITY_FIELD_NUMBER: _builtins.int
    FEATURE_FIELD_NUMBER: _builtins.int
    FEATURE_SERVICE_FIELD_NUMBER: _builtins.int
    DATA_SOURCE_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    entity: _builtins.str
    feature: _builtins.str
    feature_service: _builtins.str
    data_source: _builtins.str
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        entity: _builtins.str = ...,
        feature: _builtins.str = ...,
        feature_service: _builtins.str = ...,
        data_source: _builtins.str = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "data_source", b"data_source", "entity", b"entity", "feature", b"feature", "feature_service", b"feature_service", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListAllFeatureViewsRequest: _TypeAlias = ListAllFeatureViewsRequest  # noqa: Y015

@_typing.final
class ListAllFeatureViewsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEWS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_views(self) -> _containers.RepeatedCompositeFieldContainer[Global___AnyFeatureView]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        feature_views: _abc.Iterable[Global___AnyFeatureView] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_views", b"feature_views", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListAllFeatureViewsResponse: _TypeAlias = ListAllFeatureViewsResponse  # noqa: Y015

@_typing.final
class GetStreamFeatureViewRequest(_message.Message):
    """StreamFeatureView"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetStreamFeatureViewRequest: _TypeAlias = GetStreamFeatureViewRequest  # noqa: Y015

@_typing.final
class ListStreamFeatureViewsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListStreamFeatureViewsRequest: _TypeAlias = ListStreamFeatureViewsRequest  # noqa: Y015

@_typing.final
class ListStreamFeatureViewsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_FEATURE_VIEWS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stream_feature_views(self) -> _containers.RepeatedCompositeFieldContainer[_StreamFeatureView_pb2.StreamFeatureView]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        stream_feature_views: _abc.Iterable[_StreamFeatureView_pb2.StreamFeatureView] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "stream_feature_views", b"stream_feature_views"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListStreamFeatureViewsResponse: _TypeAlias = ListStreamFeatureViewsResponse  # noqa: Y015

@_typing.final
class GetOnDemandFeatureViewRequest(_message.Message):
    """OnDemandFeatureView"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetOnDemandFeatureViewRequest: _TypeAlias = GetOnDemandFeatureViewRequest  # noqa: Y015

@_typing.final
class ListOnDemandFeatureViewsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListOnDemandFeatureViewsRequest: _TypeAlias = ListOnDemandFeatureViewsRequest  # noqa: Y015

@_typing.final
class ListOnDemandFeatureViewsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ON_DEMAND_FEATURE_VIEWS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def on_demand_feature_views(self) -> _containers.RepeatedCompositeFieldContainer[_OnDemandFeatureView_pb2.OnDemandFeatureView]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        on_demand_feature_views: _abc.Iterable[_OnDemandFeatureView_pb2.OnDemandFeatureView] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["on_demand_feature_views", b"on_demand_feature_views", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListOnDemandFeatureViewsResponse: _TypeAlias = ListOnDemandFeatureViewsResponse  # noqa: Y015

@_typing.final
class ApplyFeatureServiceRequest(_message.Message):
    """FeatureServices"""

    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_SERVICE_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def feature_service(self) -> _FeatureService_pb2.FeatureService: ...
    def __init__(
        self,
        *,
        feature_service: _FeatureService_pb2.FeatureService | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_service", b"feature_service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "feature_service", b"feature_service", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyFeatureServiceRequest: _TypeAlias = ApplyFeatureServiceRequest  # noqa: Y015

@_typing.final
class GetFeatureServiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFeatureServiceRequest: _TypeAlias = GetFeatureServiceRequest  # noqa: Y015

@_typing.final
class ListFeatureServicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    feature_view: _builtins.str
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        feature_view: _builtins.str = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "feature_view", b"feature_view", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeatureServicesRequest: _TypeAlias = ListFeatureServicesRequest  # noqa: Y015

@_typing.final
class ListFeatureServicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_SERVICES_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_services(self) -> _containers.RepeatedCompositeFieldContainer[_FeatureService_pb2.FeatureService]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        feature_services: _abc.Iterable[_FeatureService_pb2.FeatureService] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_services", b"feature_services", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeatureServicesResponse: _TypeAlias = ListFeatureServicesResponse  # noqa: Y015

@_typing.final
class DeleteFeatureServiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteFeatureServiceRequest: _TypeAlias = DeleteFeatureServiceRequest  # noqa: Y015

@_typing.final
class ApplySavedDatasetRequest(_message.Message):
    """SavedDataset"""

    DESCRIPTOR: _descriptor.Descriptor

    SAVED_DATASET_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def saved_dataset(self) -> _SavedDataset_pb2.SavedDataset: ...
    def __init__(
        self,
        *,
        saved_dataset: _SavedDataset_pb2.SavedDataset | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["saved_dataset", b"saved_dataset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "project", b"project", "saved_dataset", b"saved_dataset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplySavedDatasetRequest: _TypeAlias = ApplySavedDatasetRequest  # noqa: Y015

@_typing.final
class GetSavedDatasetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSavedDatasetRequest: _TypeAlias = GetSavedDatasetRequest  # noqa: Y015

@_typing.final
class ListSavedDatasetsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListSavedDatasetsRequest: _TypeAlias = ListSavedDatasetsRequest  # noqa: Y015

@_typing.final
class ListSavedDatasetsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAVED_DATASETS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def saved_datasets(self) -> _containers.RepeatedCompositeFieldContainer[_SavedDataset_pb2.SavedDataset]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        saved_datasets: _abc.Iterable[_SavedDataset_pb2.SavedDataset] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "saved_datasets", b"saved_datasets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListSavedDatasetsResponse: _TypeAlias = ListSavedDatasetsResponse  # noqa: Y015

@_typing.final
class DeleteSavedDatasetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteSavedDatasetRequest: _TypeAlias = DeleteSavedDatasetRequest  # noqa: Y015

@_typing.final
class ApplyValidationReferenceRequest(_message.Message):
    """ValidationReference"""

    DESCRIPTOR: _descriptor.Descriptor

    VALIDATION_REFERENCE_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def validation_reference(self) -> _ValidationProfile_pb2.ValidationReference: ...
    def __init__(
        self,
        *,
        validation_reference: _ValidationProfile_pb2.ValidationReference | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["validation_reference", b"validation_reference"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "project", b"project", "validation_reference", b"validation_reference"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyValidationReferenceRequest: _TypeAlias = ApplyValidationReferenceRequest  # noqa: Y015

@_typing.final
class GetValidationReferenceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetValidationReferenceRequest: _TypeAlias = GetValidationReferenceRequest  # noqa: Y015

@_typing.final
class ListValidationReferencesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListValidationReferencesRequest: _TypeAlias = ListValidationReferencesRequest  # noqa: Y015

@_typing.final
class ListValidationReferencesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATION_REFERENCES_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def validation_references(self) -> _containers.RepeatedCompositeFieldContainer[_ValidationProfile_pb2.ValidationReference]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        validation_references: _abc.Iterable[_ValidationProfile_pb2.ValidationReference] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "validation_references", b"validation_references"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListValidationReferencesResponse: _TypeAlias = ListValidationReferencesResponse  # noqa: Y015

@_typing.final
class DeleteValidationReferenceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteValidationReferenceRequest: _TypeAlias = DeleteValidationReferenceRequest  # noqa: Y015

@_typing.final
class ApplyPermissionRequest(_message.Message):
    """Permissions"""

    DESCRIPTOR: _descriptor.Descriptor

    PERMISSION_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    commit: _builtins.bool
    @_builtins.property
    def permission(self) -> _Permission_pb2.Permission: ...
    def __init__(
        self,
        *,
        permission: _Permission_pb2.Permission | None = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "permission", b"permission", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyPermissionRequest: _TypeAlias = ApplyPermissionRequest  # noqa: Y015

@_typing.final
class GetPermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPermissionRequest: _TypeAlias = GetPermissionRequest  # noqa: Y015

@_typing.final
class ListPermissionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "project", b"project", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListPermissionsRequest: _TypeAlias = ListPermissionsRequest  # noqa: Y015

@_typing.final
class ListPermissionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PERMISSIONS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def permissions(self) -> _containers.RepeatedCompositeFieldContainer[_Permission_pb2.Permission]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        permissions: _abc.Iterable[_Permission_pb2.Permission] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "permissions", b"permissions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListPermissionsResponse: _TypeAlias = ListPermissionsResponse  # noqa: Y015

@_typing.final
class DeletePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    project: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeletePermissionRequest: _TypeAlias = DeletePermissionRequest  # noqa: Y015

@_typing.final
class ApplyProjectRequest(_message.Message):
    """Projects"""

    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    commit: _builtins.bool
    @_builtins.property
    def project(self) -> _Project_pb2.Project: ...
    def __init__(
        self,
        *,
        project: _Project_pb2.Project | None = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["project", b"project"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyProjectRequest: _TypeAlias = ApplyProjectRequest  # noqa: Y015

@_typing.final
class GetProjectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetProjectRequest: _TypeAlias = GetProjectRequest  # noqa: Y015

@_typing.final
class ListProjectsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    allow_cache: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        allow_cache: _builtins.bool = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "pagination", b"pagination", "sorting", b"sorting", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListProjectsRequest: _TypeAlias = ListProjectsRequest  # noqa: Y015

@_typing.final
class ListProjectsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECTS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def projects(self) -> _containers.RepeatedCompositeFieldContainer[_Project_pb2.Project]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        projects: _abc.Iterable[_Project_pb2.Project] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "projects", b"projects"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListProjectsResponse: _TypeAlias = ListProjectsResponse  # noqa: Y015

@_typing.final
class DeleteProjectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    commit: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        commit: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteProjectRequest: _TypeAlias = DeleteProjectRequest  # noqa: Y015

@_typing.final
class EntityReference(_message.Message):
    """Lineage"""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """"dataSource", "entity", "featureView", "featureService" """
    name: _builtins.str
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EntityReference: _TypeAlias = EntityReference  # noqa: Y015

@_typing.final
class EntityRelation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def source(self) -> Global___EntityReference: ...
    @_builtins.property
    def target(self) -> Global___EntityReference: ...
    def __init__(
        self,
        *,
        source: Global___EntityReference | None = ...,
        target: Global___EntityReference | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["source", b"source", "target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["source", b"source", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EntityRelation: _TypeAlias = EntityRelation  # noqa: Y015

@_typing.final
class GetRegistryLineageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    FILTER_OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    FILTER_OBJECT_NAME_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    allow_cache: _builtins.bool
    filter_object_type: _builtins.str
    filter_object_name: _builtins.str
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        filter_object_type: _builtins.str = ...,
        filter_object_name: _builtins.str = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "filter_object_name", b"filter_object_name", "filter_object_type", b"filter_object_type", "pagination", b"pagination", "project", b"project", "sorting", b"sorting"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRegistryLineageRequest: _TypeAlias = GetRegistryLineageRequest  # noqa: Y015

@_typing.final
class GetRegistryLineageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    INDIRECT_RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    RELATIONSHIPS_PAGINATION_FIELD_NUMBER: _builtins.int
    INDIRECT_RELATIONSHIPS_PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___EntityRelation]: ...
    @_builtins.property
    def indirect_relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___EntityRelation]: ...
    @_builtins.property
    def relationships_pagination(self) -> Global___PaginationMetadata: ...
    @_builtins.property
    def indirect_relationships_pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        relationships: _abc.Iterable[Global___EntityRelation] | None = ...,
        indirect_relationships: _abc.Iterable[Global___EntityRelation] | None = ...,
        relationships_pagination: Global___PaginationMetadata | None = ...,
        indirect_relationships_pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["indirect_relationships_pagination", b"indirect_relationships_pagination", "relationships_pagination", b"relationships_pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["indirect_relationships", b"indirect_relationships", "indirect_relationships_pagination", b"indirect_relationships_pagination", "relationships", b"relationships", "relationships_pagination", b"relationships_pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRegistryLineageResponse: _TypeAlias = GetRegistryLineageResponse  # noqa: Y015

@_typing.final
class GetObjectRelationshipsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_NAME_FIELD_NUMBER: _builtins.int
    INCLUDE_INDIRECT_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    object_type: _builtins.str
    object_name: _builtins.str
    include_indirect: _builtins.bool
    allow_cache: _builtins.bool
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        object_type: _builtins.str = ...,
        object_name: _builtins.str = ...,
        include_indirect: _builtins.bool = ...,
        allow_cache: _builtins.bool = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "include_indirect", b"include_indirect", "object_name", b"object_name", "object_type", b"object_type", "pagination", b"pagination", "project", b"project", "sorting", b"sorting"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetObjectRelationshipsRequest: _TypeAlias = GetObjectRelationshipsRequest  # noqa: Y015

@_typing.final
class GetObjectRelationshipsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___EntityRelation]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        relationships: _abc.Iterable[Global___EntityRelation] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "relationships", b"relationships"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetObjectRelationshipsResponse: _TypeAlias = GetObjectRelationshipsResponse  # noqa: Y015

@_typing.final
class Feature(_message.Message):
    """Feature messages"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: _builtins.int
    LAST_UPDATED_TIMESTAMP_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    feature_view: _builtins.str
    type: _builtins.str
    description: _builtins.str
    owner: _builtins.str
    @_builtins.property
    def created_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def last_updated_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        feature_view: _builtins.str = ...,
        type: _builtins.str = ...,
        description: _builtins.str = ...,
        owner: _builtins.str = ...,
        created_timestamp: _timestamp_pb2.Timestamp | None = ...,
        last_updated_timestamp: _timestamp_pb2.Timestamp | None = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_timestamp", b"created_timestamp", "last_updated_timestamp", b"last_updated_timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_timestamp", b"created_timestamp", "description", b"description", "feature_view", b"feature_view", "last_updated_timestamp", b"last_updated_timestamp", "name", b"name", "owner", b"owner", "tags", b"tags", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Feature: _TypeAlias = Feature  # noqa: Y015

@_typing.final
class ListFeaturesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    SORTING_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    feature_view: _builtins.str
    name: _builtins.str
    allow_cache: _builtins.bool
    @_builtins.property
    def pagination(self) -> Global___PaginationParams: ...
    @_builtins.property
    def sorting(self) -> Global___SortingParams: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        feature_view: _builtins.str = ...,
        name: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
        pagination: Global___PaginationParams | None = ...,
        sorting: Global___SortingParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "sorting", b"sorting"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "feature_view", b"feature_view", "name", b"name", "pagination", b"pagination", "project", b"project", "sorting", b"sorting"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeaturesRequest: _TypeAlias = ListFeaturesRequest  # noqa: Y015

@_typing.final
class ListFeaturesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURES_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def features(self) -> _containers.RepeatedCompositeFieldContainer[Global___Feature]: ...
    @_builtins.property
    def pagination(self) -> Global___PaginationMetadata: ...
    def __init__(
        self,
        *,
        features: _abc.Iterable[Global___Feature] | None = ...,
        pagination: Global___PaginationMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["features", b"features", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFeaturesResponse: _TypeAlias = ListFeaturesResponse  # noqa: Y015

@_typing.final
class GetFeatureRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ALLOW_CACHE_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    feature_view: _builtins.str
    name: _builtins.str
    allow_cache: _builtins.bool
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        feature_view: _builtins.str = ...,
        name: _builtins.str = ...,
        allow_cache: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cache", b"allow_cache", "feature_view", b"feature_view", "name", b"name", "project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFeatureRequest: _TypeAlias = GetFeatureRequest  # noqa: Y015
