# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feast/core/DynamoDBTable.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66\x65\x61st/core/DynamoDBTable.proto\x12\nfeast.core\"-\n\rDynamoDBTable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\tBW\n\x10\x66\x65\x61st.proto.coreB\x12\x44ynamoDBTableProtoZ/github.com/feast-dev/feast/go/protos/feast/coreb\x06proto3')



_DYNAMODBTABLE = DESCRIPTOR.message_types_by_name['DynamoDBTable']
DynamoDBTable = _reflection.GeneratedProtocolMessageType('DynamoDBTable', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMODBTABLE,
  '__module__' : 'feast.core.DynamoDBTable_pb2'
  # @@protoc_insertion_point(class_scope:feast.core.DynamoDBTable)
  })
_sym_db.RegisterMessage(DynamoDBTable)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020feast.proto.coreB\022DynamoDBTableProtoZ/github.com/feast-dev/feast/go/protos/feast/core'
  _DYNAMODBTABLE._serialized_start=46
  _DYNAMODBTABLE._serialized_end=91
# @@protoc_insertion_point(module_scope)
