"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import feast.core.DataSource_pb2
import feast.core.Feature_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class FeatureView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SPEC_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int

    @property
    def spec(self) -> global___FeatureViewSpec: ...

    @property
    def meta(self) -> global___FeatureViewMeta: ...

    def __init__(self,
        *,
        spec : typing.Optional[global___FeatureViewSpec] = ...,
        meta : typing.Optional[global___FeatureViewMeta] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"meta",b"meta",u"spec",b"spec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"meta",b"meta",u"spec",b"spec"]) -> None: ...
global___FeatureView = FeatureView

class FeatureViewSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    ENTITIES_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    INPUT_FIELD_NUMBER: builtins.int
    ONLINE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    project: typing.Text = ...
    entities: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...
    online: builtins.bool = ...

    @property
    def features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[feast.core.Feature_pb2.FeatureSpecV2]: ...

    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...

    @property
    def ttl(self) -> google.protobuf.duration_pb2.Duration: ...

    @property
    def input(self) -> feast.core.DataSource_pb2.DataSource: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        project : typing.Text = ...,
        entities : typing.Optional[typing.Iterable[typing.Text]] = ...,
        features : typing.Optional[typing.Iterable[feast.core.Feature_pb2.FeatureSpecV2]] = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        ttl : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        input : typing.Optional[feast.core.DataSource_pb2.DataSource] = ...,
        online : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"input",b"input",u"ttl",b"ttl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"entities",b"entities",u"features",b"features",u"input",b"input",u"name",b"name",u"online",b"online",u"project",b"project",u"tags",b"tags",u"ttl",b"ttl"]) -> None: ...
global___FeatureViewSpec = FeatureViewSpec

class FeatureViewMeta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    LAST_UPDATED_TIMESTAMP_FIELD_NUMBER: builtins.int

    @property
    def created_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def last_updated_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        created_timestamp : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_updated_timestamp : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"created_timestamp",b"created_timestamp",u"last_updated_timestamp",b"last_updated_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"created_timestamp",b"created_timestamp",u"last_updated_timestamp",b"last_updated_timestamp"]) -> None: ...
global___FeatureViewMeta = FeatureViewMeta
