"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2020 The Feast Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from feast.core import Aggregation_pb2 as _Aggregation_pb2
from feast.core import DataSource_pb2 as _DataSource_pb2
from feast.core import FeatureViewProjection_pb2 as _FeatureViewProjection_pb2
from feast.core import FeatureView_pb2 as _FeatureView_pb2
from feast.core import Feature_pb2 as _Feature_pb2
from feast.core import Transformation_pb2 as _Transformation_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OnDemandFeatureView(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPEC_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def spec(self) -> Global___OnDemandFeatureViewSpec:
        """User-specified specifications of this feature view."""

    @_builtins.property
    def meta(self) -> Global___OnDemandFeatureViewMeta: ...
    def __init__(
        self,
        *,
        spec: Global___OnDemandFeatureViewSpec | None = ...,
        meta: Global___OnDemandFeatureViewMeta | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OnDemandFeatureView: _TypeAlias = OnDemandFeatureView  # noqa: Y015

@_typing.final
class OnDemandFeatureViewSpec(_message.Message):
    """Next available id: 9"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SourcesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___OnDemandSource: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___OnDemandSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    PROJECT_FIELD_NUMBER: _builtins.int
    FEATURES_FIELD_NUMBER: _builtins.int
    SOURCES_FIELD_NUMBER: _builtins.int
    USER_DEFINED_FUNCTION_FIELD_NUMBER: _builtins.int
    FEATURE_TRANSFORMATION_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    WRITE_TO_ONLINE_STORE_FIELD_NUMBER: _builtins.int
    ENTITIES_FIELD_NUMBER: _builtins.int
    ENTITY_COLUMNS_FIELD_NUMBER: _builtins.int
    SINGLETON_FIELD_NUMBER: _builtins.int
    AGGREGATIONS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Name of the feature view. Must be unique. Not updated."""
    project: _builtins.str
    """Name of Feast project that this feature view belongs to."""
    description: _builtins.str
    """Description of the on demand feature view."""
    owner: _builtins.str
    """Owner of the on demand feature view."""
    mode: _builtins.str
    write_to_online_store: _builtins.bool
    singleton: _builtins.bool
    @_builtins.property
    def features(self) -> _containers.RepeatedCompositeFieldContainer[_Feature_pb2.FeatureSpecV2]:
        """List of features specifications for each feature defined with this feature view."""

    @_builtins.property
    def sources(self) -> _containers.MessageMap[_builtins.str, Global___OnDemandSource]:
        """Map of sources for this feature view."""

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def user_defined_function(self) -> Global___UserDefinedFunction: ...
    @_builtins.property
    def feature_transformation(self) -> _Transformation_pb2.FeatureTransformationV2:
        """Oneof with {user_defined_function, on_demand_substrait_transformation}"""

    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """User defined metadata."""

    @_builtins.property
    def entities(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """List of names of entities associated with this feature view."""

    @_builtins.property
    def entity_columns(self) -> _containers.RepeatedCompositeFieldContainer[_Feature_pb2.FeatureSpecV2]:
        """List of specifications for each entity defined as part of this feature view."""

    @_builtins.property
    def aggregations(self) -> _containers.RepeatedCompositeFieldContainer[_Aggregation_pb2.Aggregation]:
        """Aggregation definitions"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        project: _builtins.str = ...,
        features: _abc.Iterable[_Feature_pb2.FeatureSpecV2] | None = ...,
        sources: _abc.Mapping[_builtins.str, Global___OnDemandSource] | None = ...,
        user_defined_function: Global___UserDefinedFunction | None = ...,
        feature_transformation: _Transformation_pb2.FeatureTransformationV2 | None = ...,
        description: _builtins.str = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        owner: _builtins.str = ...,
        mode: _builtins.str = ...,
        write_to_online_store: _builtins.bool = ...,
        entities: _abc.Iterable[_builtins.str] | None = ...,
        entity_columns: _abc.Iterable[_Feature_pb2.FeatureSpecV2] | None = ...,
        singleton: _builtins.bool = ...,
        aggregations: _abc.Iterable[_Aggregation_pb2.Aggregation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_transformation", b"feature_transformation", "user_defined_function", b"user_defined_function"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aggregations", b"aggregations", "description", b"description", "entities", b"entities", "entity_columns", b"entity_columns", "feature_transformation", b"feature_transformation", "features", b"features", "mode", b"mode", "name", b"name", "owner", b"owner", "project", b"project", "singleton", b"singleton", "sources", b"sources", "tags", b"tags", "user_defined_function", b"user_defined_function", "write_to_online_store", b"write_to_online_store"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OnDemandFeatureViewSpec: _TypeAlias = OnDemandFeatureViewSpec  # noqa: Y015

@_typing.final
class OnDemandFeatureViewMeta(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREATED_TIMESTAMP_FIELD_NUMBER: _builtins.int
    LAST_UPDATED_TIMESTAMP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def created_timestamp(self) -> _timestamp_pb2.Timestamp:
        """Time where this Feature View is created"""

    @_builtins.property
    def last_updated_timestamp(self) -> _timestamp_pb2.Timestamp:
        """Time where this Feature View is last updated"""

    def __init__(
        self,
        *,
        created_timestamp: _timestamp_pb2.Timestamp | None = ...,
        last_updated_timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_timestamp", b"created_timestamp", "last_updated_timestamp", b"last_updated_timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_timestamp", b"created_timestamp", "last_updated_timestamp", b"last_updated_timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OnDemandFeatureViewMeta: _TypeAlias = OnDemandFeatureViewMeta  # noqa: Y015

@_typing.final
class OnDemandSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_VIEW_FIELD_NUMBER: _builtins.int
    FEATURE_VIEW_PROJECTION_FIELD_NUMBER: _builtins.int
    REQUEST_DATA_SOURCE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_view(self) -> _FeatureView_pb2.FeatureView: ...
    @_builtins.property
    def feature_view_projection(self) -> _FeatureViewProjection_pb2.FeatureViewProjection: ...
    @_builtins.property
    def request_data_source(self) -> _DataSource_pb2.DataSource: ...
    def __init__(
        self,
        *,
        feature_view: _FeatureView_pb2.FeatureView | None = ...,
        feature_view_projection: _FeatureViewProjection_pb2.FeatureViewProjection | None = ...,
        request_data_source: _DataSource_pb2.DataSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_view", b"feature_view", "feature_view_projection", b"feature_view_projection", "request_data_source", b"request_data_source", "source", b"source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_view", b"feature_view", "feature_view_projection", b"feature_view_projection", "request_data_source", b"request_data_source", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_source: _TypeAlias = _typing.Literal["feature_view", "feature_view_projection", "request_data_source"]  # noqa: Y015
    _WhichOneofArgType_source: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_source) -> _WhichOneofReturnType_source | None: ...

Global___OnDemandSource: _TypeAlias = OnDemandSource  # noqa: Y015

@_deprecated("""This message has been marked as deprecated using proto message options.""")
@_typing.final
class UserDefinedFunction(_message.Message):
    """Serialized representation of python function."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    BODY_FIELD_NUMBER: _builtins.int
    BODY_TEXT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The function name"""
    body: _builtins.bytes
    """The python-syntax function body (serialized by dill)"""
    body_text: _builtins.str
    """The string representation of the udf"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        body: _builtins.bytes = ...,
        body_text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "body_text", b"body_text", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserDefinedFunction: _TypeAlias = UserDefinedFunction  # noqa: Y015

@_typing.final
class OnDemandFeatureViewList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ONDEMANDFEATUREVIEWS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ondemandfeatureviews(self) -> _containers.RepeatedCompositeFieldContainer[Global___OnDemandFeatureView]: ...
    def __init__(
        self,
        *,
        ondemandfeatureviews: _abc.Iterable[Global___OnDemandFeatureView] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ondemandfeatureviews", b"ondemandfeatureviews"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OnDemandFeatureViewList: _TypeAlias = OnDemandFeatureViewList  # noqa: Y015
