"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Policy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    ROLE_BASED_POLICY_FIELD_NUMBER: builtins.int
    GROUP_BASED_POLICY_FIELD_NUMBER: builtins.int
    NAMESPACE_BASED_POLICY_FIELD_NUMBER: builtins.int
    COMBINED_GROUP_NAMESPACE_POLICY_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the policy."""
    project: builtins.str
    """Name of Feast project."""
    @property
    def role_based_policy(self) -> global___RoleBasedPolicy: ...
    @property
    def group_based_policy(self) -> global___GroupBasedPolicy: ...
    @property
    def namespace_based_policy(self) -> global___NamespaceBasedPolicy: ...
    @property
    def combined_group_namespace_policy(self) -> global___CombinedGroupNamespacePolicy: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        project: builtins.str = ...,
        role_based_policy: global___RoleBasedPolicy | None = ...,
        group_based_policy: global___GroupBasedPolicy | None = ...,
        namespace_based_policy: global___NamespaceBasedPolicy | None = ...,
        combined_group_namespace_policy: global___CombinedGroupNamespacePolicy | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["combined_group_namespace_policy", b"combined_group_namespace_policy", "group_based_policy", b"group_based_policy", "namespace_based_policy", b"namespace_based_policy", "policy_type", b"policy_type", "role_based_policy", b"role_based_policy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["combined_group_namespace_policy", b"combined_group_namespace_policy", "group_based_policy", b"group_based_policy", "name", b"name", "namespace_based_policy", b"namespace_based_policy", "policy_type", b"policy_type", "project", b"project", "role_based_policy", b"role_based_policy"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["policy_type", b"policy_type"]) -> typing_extensions.Literal["role_based_policy", "group_based_policy", "namespace_based_policy", "combined_group_namespace_policy"] | None: ...

global___Policy = Policy

class RoleBasedPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROLES_FIELD_NUMBER: builtins.int
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of roles in this policy."""
    def __init__(
        self,
        *,
        roles: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["roles", b"roles"]) -> None: ...

global___RoleBasedPolicy = RoleBasedPolicy

class GroupBasedPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUPS_FIELD_NUMBER: builtins.int
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of groups in this policy."""
    def __init__(
        self,
        *,
        groups: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["groups", b"groups"]) -> None: ...

global___GroupBasedPolicy = GroupBasedPolicy

class NamespaceBasedPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACES_FIELD_NUMBER: builtins.int
    @property
    def namespaces(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of namespaces in this policy."""
    def __init__(
        self,
        *,
        namespaces: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["namespaces", b"namespaces"]) -> None: ...

global___NamespaceBasedPolicy = NamespaceBasedPolicy

class CombinedGroupNamespacePolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUPS_FIELD_NUMBER: builtins.int
    NAMESPACES_FIELD_NUMBER: builtins.int
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of groups in this policy."""
    @property
    def namespaces(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of namespaces in this policy."""
    def __init__(
        self,
        *,
        groups: collections.abc.Iterable[builtins.str] | None = ...,
        namespaces: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["groups", b"groups", "namespaces", b"namespaces"]) -> None: ...

global___CombinedGroupNamespacePolicy = CombinedGroupNamespacePolicy
