FROM registry.access.redhat.com/ubi9/python-311@sha256:9d3578927c6168e364f963b642fb15d5c4b1224a31c11da2ae970f05708724ae

# OS Packages needs to be installed as root
USER 0

# Copy Power prebuild script
COPY prebuild-power.sh /prebuild-power.sh
RUN chmod +x /prebuild-power.sh

# Prefetched artifacts
RUN cp /cachi2/output/deps/generic/duckdb-v1.1.3.tar.gz /tmp/ && \
    cp /cachi2/output/deps/generic/apache-arrow-17.0.0.tar.gz /tmp/

# Extract (Power only)
RUN if [ "$(uname -m)" = "ppc64le" ]; then \
        tar -xzf /tmp/duckdb-v1.1.3.tar.gz -C /tmp && \
        tar -xzf /tmp/apache-arrow-17.0.0.tar.gz -C /tmp; \
    fi

# Run prebuild script conditionally (Power only)
RUN if [ "$(uname -m)" = "ppc64le" ]; then \
        echo "Power architecture detected. Running prebuild script..."; \
        /prebuild-power.sh && pip install /wheelhouse/*.whl; \
        echo "Listing built wheels:" && ls -lh /wheelhouse; \
    else \
        echo "Non-Power architecture detected; skipping Power prebuild"; \
    fi

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json

# default user
USER 1001

LABEL com.redhat.component="odh-feature-server" \
      name="odh-feature-server-rhel9" \
      description="odh-feature-server" \
      summary="odh-feature-server" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-feature-server" \
      io.k8s.description="odh-feature-server"

