---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: feast-example-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-example-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-example-client
  template:
    metadata:
      labels:
        app: feast-example-client
    spec:
      serviceAccountName: feast-example-client
      initContainers:
        - name: init-registry
          command:
            - sh
            - '-c'
            - 'until grpcurl -H "authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -plaintext -d '''' -format text feast-example-registry.feast.svc.cluster.local:80 grpc.health.v1.Health/Check; do echo waiting for registry; sleep 2; done'
          image: 'fullstorydev/grpcurl:v1.9.1-alpine'
      containers:
        - name: client
          image: 'quay.io/tchughesiv/feature-server:0.42.0-duckdb'
          imagePullPolicy: Always
          workingDir: /feast-init
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: client-feature-store-config
              mountPath: /feast-client
              readOnly: true
            - name: shared-data
              mountPath: /feast-init
      volumes:
        - name: client-feature-store-config
          configMap:
            name: feast-example-client
        - name: shared-data
          emptyDir: {}
