---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: feast-example-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-example-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-example-client
  template:
    metadata:
      labels:
        app: feast-example-client
    spec:
      serviceAccountName: feast-example-client
      initContainers:
        - name: init-feature-store
          image: 'quay.io/tchughesiv/feature-server:0.42.0-duckdb'
          imagePullPolicy: Always
          workingDir: /feast-init
          env:
            - name: MPLCONFIGDIR
              value: /feast-init/matplotlib
          envFrom:
            - secretRef:
                name: postgres-secret
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting feast initialization job...";
              mkdir feast-credit-score-local-tutorial;
              tar vfx /f43b44b.tar.gz -C feast-credit-score-local-tutorial --strip-components 1;
              cp -f /feature_store.yaml /feast-init/feast-credit-score-local-tutorial/feature_repo/;
              cd /feast-init/feast-credit-score-local-tutorial/feature_repo;
              cat feature_store.yaml;
          volumeMounts:
            - name: shared-data
              mountPath: /feast-init
      containers:
        - name: client
          image: 'quay.io/tchughesiv/feature-server:0.42.0-duckdb'
          imagePullPolicy: Always
          workingDir: /feast-init/feast-credit-score-local-tutorial/feature_repo
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
          env:
            - name: MPLCONFIGDIR
              value: /feast-init/matplotlib
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: shared-data
              mountPath: /feast-init
        - name: online
          image: 'quay.io/tchughesiv/feature-server:0.42.0-duckdb'
          imagePullPolicy: Always
          workingDir: /feast-init/feast-credit-score-local-tutorial/feature_repo
          readinessProbe:
            httpGet:
              path: /health
              port: 6566
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          command:
            - feast
            - serve
            - '-h'
            - 0.0.0.0
            - '-p'
            - '6566'
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
          env:
            - name: MPLCONFIGDIR
              value: /feast-init/matplotlib
          envFrom:
            - secretRef:
                name: postgres-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 6566
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: online
              containerPort: 6566
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: /feast-init
        - name: registry
          image: 'quay.io/tchughesiv/feature-server:0.42.0-duckdb'
          imagePullPolicy: Always
          workingDir: /feast-init/feast-credit-score-local-tutorial/feature_repo
          readinessProbe:
            tcpSocket:
              port: 6570
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          command:
            - feast
            - serve_registry
            - '-p'
            - '6570'
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
          env:
            - name: MPLCONFIGDIR
              value: /feast-init/matplotlib
          envFrom:
            - secretRef:
                name: postgres-secret
          livenessProbe:
            tcpSocket:
              port: 6570
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: registry
              containerPort: 6570
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: /feast-init
      volumes:
        - name: shared-data
          emptyDir: {}
