FROM feastdev/feature-server:0.42.0

RUN pip install --no-cache-dir "feast[aws,gcp,snowflake,redis,go,mysql,postgres,opentelemetry,grpcio,k8s,duckdb]" \
    streamlit \
    shap \
    pandas \
    scikit-learn \
    matplotlib
