apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "feature-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feature-server.name" . }}
    component: serving
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "feature-server.name" . }}
      component: serving
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "feature-server.name" . }}
        component: serving
        release: {{ .Release.Name }}
      {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: FEATURE_STORE_YAML_BASE64
          value: {{ .Values.feature_store_yaml_base64 }}

        {{- range $key, $value := .Values.envOverrides }}
        - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
          {{- if eq (kindOf $value) "map" }}
          valueFrom:
            {{- toYaml $value | nindent 12 }}
          {{- else }}
          value: {{ $value | quote }}
          {{- end }}
        {{- end }}

        command:
        - "feast"
        - "serve"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "{{ .Values.service.port }}"

        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP

        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}

        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
