apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "feature-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "feature-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or (not .Values.existingSecret) .Values.podAnnotations }}
      annotations:
        {{- if not .Values.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "feature-server.selectorLabels" . | nindent 8 }}
      {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.secrets }}
      volumes:
      {{- range $secret := .Values.secrets }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
      {{- end }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: FEATURE_STORE_YAML_BASE64
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (include "feature-server.fullname" .) }}
              key: feature_store_yaml_base64

        {{- range $key, $value := .Values.envOverrides }}
        - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
          {{- if eq (kindOf $value) "map" }}
          valueFrom:
            {{- toYaml $value | nindent 12 }}
          {{- else }}
          value: {{ $value | quote }}
          {{- end }}
        {{- end }}

        command:
        - "feast"
        - "serve"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "{{ .Values.service.port }}"

        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP

        {{- if .Values.secrets }}
        volumeMounts:
        {{- range $secret := .Values.secrets }}
        - name: {{ $secret }}
          mountPath: "/etc/secrets/{{ $secret }}"
          readOnly: true
        {{- end }}
        {{- end }}

        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}

        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
