{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "feature-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  feature_store_yaml_base64: {{ .Values.feature_store_yaml_base64 | quote }}
{{- end }}
