apiVersion: v1
kind: Service
metadata:
  name: {{ template "feature-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 2 }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "feature-server.selectorLabels" . | nindent 4 }}
