{
 "title": "Feast Features Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values(feast_project_name)"
   },
   {
    "name": "feature",
    "query": "label_values(feast_ingestion_feature_value_presence_count{feast_project_name=\"[[project]]\"},feast_feature_name)"
   }
  ]
 },
 "panels": [
  { "title": "Constraint Violation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Value",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(feast_ingestion_feature_value_max - on(feast_project_name,feast_feature_name) feast_ingestion_feature_value_domain_max) > 0"
    },
    {
     "expr": "(feast_ingestion_feature_value_domain_min - on(feast_project_name,feast_feature_name) feast_ingestion_feature_value_min) > 0"
    }
   ]
  },
  {
   "title": "Presence Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feast_ingestion_feature_presence_min_count - on (feast_feature_name, feast_project_name)  increase(feast_ingestion_feature_value_presence_count[5m]) > 0"
    }
   ]
  },
  {
   "title": "Presence Fraction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feast_ingestion_feature_presence_min_fraction - on (feast_feature_name, feast_project_name) increase(feast_ingestion_feature_value_presence_count[5m]) / (\nincrease(feast_ingestion_feature_value_presence_count[5m]) +\nincrease(feast_ingestion_feature_value_missing_count[5m])\n) > 0"
    }
   ]
  },
  { "title": "Feature Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "feature" },
  {
   "title": "Feature Value - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feast_ingestion_feature_value_min{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_val"
    },
    {
     "expr": "feast_ingestion_feature_value_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_val"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_min{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_domain"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_domain"
    }
   ]
  },
  {
   "title": "Presence Count - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}[$__range])",
     "legendFormat": "count"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "feature_presence_min_count"
    }
   ]
  },
  {
   "title": "Presence Fraction - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) / (\nincrease(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) + \nincrease(feast_ingestion_feature_value_missing_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range])\n)",
     "legendFormat": "fraction"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_fraction{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}",
     "legendFormat": "min_fraction"
    }
   ]
  },
  { "title": "Feature Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Feature Value - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feast_ingestion_feature_value_min{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_val"
    },
    {
     "expr": "feast_ingestion_feature_value_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_val"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_min{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_domain"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_domain"
    }
   ]
  },
  {
   "title": "Presence Count - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}[$__range])",
     "legendFormat": "count"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "feature_presence_min_count"
    }
   ]
  },
  {
   "title": "Presence Fraction - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) / (\nincrease(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) + \nincrease(feast_ingestion_feature_value_missing_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range])\n)",
     "legendFormat": "fraction"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_fraction{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}",
     "legendFormat": "min_fraction"
    }
   ]
  },
  { "title": "Feature Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Feature Value - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feast_ingestion_feature_value_min{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_val"
    },
    {
     "expr": "feast_ingestion_feature_value_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_val"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_min{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "min_domain"
    },
    {
     "expr": "feast_ingestion_feature_value_domain_max{feast_project_name=\"[[project]]\",feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "max_domain"
    }
   ]
  },
  {
   "title": "Presence Count - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}[$__range])",
     "legendFormat": "count"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_count{feast_project_name=\"[[project]]\", feast_feature_name=~\"[[feature]]\"}",
     "legendFormat": "feature_presence_min_count"
    }
   ]
  },
  {
   "title": "Presence Fraction - [[feature]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) / (\nincrease(feast_ingestion_feature_value_presence_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range]) + \nincrease(feast_ingestion_feature_value_missing_count{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}[$__range])\n)",
     "legendFormat": "fraction"
    },
    {
     "expr": "feast_ingestion_feature_presence_min_fraction{feast_feature_name=~\"[[feature]]\", feast_project_name=\"[[project]]\"}",
     "legendFormat": "min_fraction"
    }
   ]
  }
 ]
}