apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/feast?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "stable"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: odh-feature-server-ci
    pipelines.appstudio.openshift.io/type: build
  name: odh-feature-server-on-release-push
  namespace: open-data-hub-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/opendatahub/feature-server:v0.62.0
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: sdk/python/feast/infra/feature_servers/multicloud 
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-feature-server
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}