FLAG_ALPHA_FEATURES_NAME = "enable_alpha_features"
FLAG_ON_DEMAND_TRANSFORM_NAME = "enable_on_demand_transforms"
FLAG_PYTHON_FEATURE_SERVER_NAME = "enable_python_feature_server"
ENV_FLAG_IS_TEST = "IS_TEST"
ENV_FLAG_ENABLE_USAGE = "FEAST_USAGE"

FLAG_NAMES = {
    FLAG_ALPHA_FEATURES_NAME,
    FLAG_ON_DEMAND_TRANSFORM_NAME,
    FLAG_PYTHON_FEATURE_SERVER_NAME,
}
